version: '2'
services:
  web:
    image: fpfis/httpd-php:8.1-dev
    working_dir: ${PWD}
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:${PWD}      
    environment:
      DOCUMENT_ROOT: ${PWD}/web      
      NEXTCLOUD_USER:
      NEXTCLOUD_PASS:
      GITHUB_API_TOKEN:
      GITLAB_API_TOKEN:
      QA_API_BASIC_AUTH:
      QA_WEBSITE_URL:ENV: "development"
      PHP_MEMORY_LIMIT: "512M"
      # XDEBUG CONFIGURATION.
      XDEBUG_CONFIG: idekey=PHPSTORM client_port=9003 client_host=172.17.0.1 log=/tmp/xdebug.log
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env

  mysql:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    environment:
      - DISPLAY=:99
    ports:
      - "5900:5900"
    expose:
      - 4444

volumes:
  mysql:
